### ISSUE TITLE
Feature | Translation needed 📋

### ISSUE THREAD

**Issue by Neosoulink** [puxiao/threejs-tutorial#10]
## About this issue

Hello @puxiao, I appreciated reading your tutorial and I believe many other people will think the same

But the main issue with your tutorial is that it's only in **Chinese**. 
If an **English** version of this is released, I'm convinced it will help many ❤

**Comment by puxiao** [comment]
In fact, this tutorial of mine is my study notes from the official three.js tutorial. You can directly read the official English tutorial.
https://threejs.org/manual/#en/fundamentals
