### ISSUE TITLE
03 编写HelloThreejs 章节发现文字书写有误

### ISSUE THREAD

**Issue by 1509688043** [puxiao/threejs-tutorial#13]
03 编写HelloThreejs 章节内发现有两处单词写错了，虽问题不大，但是看到了还是给楼主反馈下

位于：第3环节：创建Three.js基础3大元素、场景可见元素 > 基础3大元素：>场景 > Scen 
位于：补充说明：你应该发现，除了 场景(Scen)、网格(Mesh) 之外，其他的元素我都注明 “本文示例采用的是...”。
Scene 误写成了 Scen 。

**Comment by puxiao** [comment]
LGTM
