### ISSUE TITLE
建议在文章里面增加一些图

### ISSUE THREAD

**Issue by Yunkou** [puxiao/threejs-tutorial#3]
半天撸到第12章越来越干了，需要增加一些图辅助理解。

**Comment by puxiao** [comment]
之前写的时候确实没有想那么多，当时想如果配图，估计写的速度会下降。
将就着看吧。
我最近新开始要写一套关于 WebGPU (https://github.com/puxiao/webgpu-tutorial) 的教程，这个我打算配图。
