### ISSUE TITLE
非常棒的教程

### ISSUE THREAD

**Issue by FEJackFly** [puxiao/threejs-tutorial#9]
17节 对 requestAnimationFrame 的描述 有点点不同的见解哈
**“也就是意味着，无论任何时候，我们都会在每一帧上进行场景渲染。”**

setInterval 这类会一直定时执行
而 requestAnimationFrame 在浏览器标签页 或切换桌面的时候会自动停止 （电脑性能不足是也会 降帧率 > 16毫秒执行）

**Comment by puxiao** [comment]
嗯，在这个上下文语境中，你理解怎么回事就好。
推荐你一定要去 B 站看看 3blue1brown 的 线性代数本质：https://www.bilibili.com/video/BV1ys411472E/?spm_id_from=333.999.0.0

**Comment by FEJackFly** [comment]
https://www.bilibili.com/video/BV1ys411472E/?spm_id_from=333.999.0.0

视频不见了

**Comment by puxiao** [comment]
https://space.bilibili.com/88461692/channel/seriesdetail?sid=1528927
